POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS Code REST client is pretty pretty pretty good",
    "important": false,
    "userId": "5ee25203ebcda90578387657"
}